export const openapi = {
  openapi: '3.0.3',
  info: { title: 'Apartment Marketplace API', version: '1.0.0', description: 'REST API for the apartment marketplace platform.' },
  servers: [{ url: 'http://localhost:5000/api/v1' }],
  tags: [{ name: 'Auth' }, { name: 'Marketplace' }, { name: 'Commerce' }, { name: 'Admin' }],
  paths: {
    '/health': { get: { tags: ['Marketplace'], summary: 'API and database health' } },
    '/auth/request-otp': { post: { tags: ['Auth'], summary: 'Request local dummy OTP' } },
    '/auth/verify-otp': { post: { tags: ['Auth'], summary: 'Verify OTP and issue tokens' } },
    '/auth/me': { get: { tags: ['Auth'], summary: 'Get current authenticated user' } },
    '/home': { get: { tags: ['Marketplace'], summary: 'Get scoped customer home data' } },
    '/apartments': { get: { tags: ['Marketplace'], summary: 'List active apartments' } },
    '/sellers': { get: { tags: ['Marketplace'], summary: 'List sellers eligible for current apartment' } },
    '/sellers/{sellerId}': { get: { tags: ['Marketplace'], summary: 'Get scoped seller storefront', parameters: [{ name: 'sellerId', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }] } },
    '/orders': { post: { tags: ['Commerce'], summary: 'Create transactional checkout order' }, get: { tags: ['Commerce'], summary: 'List customer orders' } },
    '/important-alerts': { get: { tags: ['Marketplace'], summary: 'List active apartment-scoped important alerts with user read/dismiss state' } },
    '/notifications/{notificationId}/dismiss': { post: { tags: ['Marketplace'], summary: 'Dismiss a customer notification' } },
    '/seller/orders': { get: { tags: ['Commerce'], summary: 'List filterable seller order queue' } },
    '/reports/seller/summary': { get: { tags: ['Commerce'], summary: 'Get filtered seller sales summary' } },
    '/reports/seller/summary.pdf': { get: { tags: ['Commerce'], summary: 'Download filtered seller summary PDF' } },
    '/delivery/orders': { get: { tags: ['Delivery'], summary: 'List delivery orders with optional apartment/seller/status grouping' } },
    '/search': { get: { tags: ['Customer'], summary: 'Search visible sellers, products, and categories' } },
    '/sellers/{sellerId}/reviews': { get: { tags: ['Customer'], summary: 'List seller rating summary and reviews' } },
    '/seller/settings': { get: { tags: ['Seller'], summary: 'Read seller profile and operating settings' }, patch: { tags: ['Seller'], summary: 'Update seller profile and operating settings' } },
    '/admin/settings/home-seller-display-mode': { get: { tags: ['Admin'], summary: 'Read home seller display mode' }, patch: { tags: ['Admin'], summary: 'Update home seller display mode' } },
    '/admin/alerts': { get: { tags: ['Admin'], summary: 'List important alerts' }, post: { tags: ['Admin'], summary: 'Create targeted important alert' } },
    '/uploads/image': { post: { tags: ['Marketplace'], summary: 'Store a validated local image data URL' } },
  },
};
